### ISSUE TITLE
404 error for a private repo.

### ISSUE THREAD

**Issue by nashibao** [RuiAAPeres/OctifyIssues#5]
I have received notifications successfully. But can't open these links with 404 error..

**Comment by RuiAAPeres** [comment]
hi @nashibao I think this is related to issues that get deleted after the notification has been fired. The only thing I can do is to display a meaningful message. What do you think?

**Comment by nashibao** [comment]
@RuiAAPeres 
Hmm.. I don't think so. I can receive successfully all notifications from public repo, but I can't receive from private (and organization) repo even once.

**Comment by RuiAAPeres** [comment]
@nashibao ok I got it. I will see how I can solve this. Thanks.

**Comment by RuiAAPeres** [comment]
@nashibao I found the issue. Would you mind login again, when you reach a private repo? There are two things happening:
- The native login you see. Since I only watch public repos I never had any issue checking out private Notification's details.
- The web login, since I use a `UIWebView` to show the details of a notification, if you reach a private repo, you will need to login again.

Right now you won't be able to do it, as I don't provide a way for you to do it from the app, but I will on the next version. So your workflow will be the following:
- Login into the app
- See a list of notifications
- Get inside one
  - If it's a public one, then everything is fine
  - If it's a private one you will receive a 404 and asked to log in again via a `UIWebView` so a session cookie can be stored in the app.

**Comment by nashibao** [comment]
@RuiAAPeres I'm sorry, I found this comment just now. I will check the issue later! thanks!
